@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmltIjoiMTIzMjIwMTE2IiwibmFtYSI6ImhhZml6aCIsInJvbGUiOiJtYWhhc2lzd2EiLCJpYXQiOjE3NDg3OTIxMTYsImV4cCI6MTc0ODc5NTcxNn0.u8uISyS1r4trbhhxe369jsgsqaxRfQStdzwRLMwfjL8

### LOGIN
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "nim": "123220116",
  "password": "123"
}

### GET ALL USERS (admin only)
GET http://localhost:5000/users
Authorization: Bearer {{token}}

### GET USER BY ID (admin only)
GET http://localhost:5000/users/2
Authorization: Bearer {{token}}

### CREATE USER (admin only)
POST http://localhost:5000/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nama": "admin",
  "nim": "000000",
  "email": "admin@mail.com",
  "password": "000000",
  "role": "admin"
}

### UPDATE USER (admin only)
PUT http://localhost:5000/users/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nama": "Andi Updated",
  "email": "andiupdate@mail.com"
}

### DELETE USER (admin only)
DELETE http://localhost:5000/users/2
Authorization: Bearer {{token}}

### GET ALL ADUAN (admin or mahasiswa)
GET http://localhost:5000/aduan
Authorization: Bearer {{token}}

### GET ADUAN BY ID
GET http://localhost:5000/aduan/1
Authorization: Bearer {{token}}

### CREATE ADUAN (mahasiswa only)
POST http://localhost:5000/aduan
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "judul": "Keluhan Wifi kampus",
  "isi": "Wifi lambat di ruang kuliah",
  "kategori": "Layanan Teknologi dan Informasi",
  "status": "pending"
}

### UPDATE ADUAN (admin only)
PUT http://localhost:5000/aduan/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "judul": "Keluhan Wifi diperbarui",
  "isi": "Wifi sering putus",
  "status": "proses"
}

### DELETE ADUAN (admin only)
DELETE http://localhost:5000/aduan/1
Authorization: Bearer {{token}}
